
#ifndef AP_POWERDOWNWAKEUP_H
    #define AP_POWERDOWNWAKEUP_H
#ifdef  AP_POWERDOWNWAKEUP_GLOBALS
    #define AP_POWERDOWNWAKEUP_EXT
#else
    #define AP_POWERDOWNWAKEUP_EXT extern
#endif  

#define CON_WAKEUP_ONEDAY_TIME (3)
#define CON_WAKEUP_REMOTE_TIME (7*24*60)
#define CON_ALLLOSSVOLTAGE_TIME (10*24*60)
#if(CONFIG_METER_AREA_MODE==CONFIG_METER_AREA_MODE_SHANGHAI)
#define CON_WAKEUP_HAND_SECOND_TIME 0
#else
#define CON_WAKEUP_HAND_SECOND_TIME 2 // 3
#endif
#define CON_WAKEUP_REMOTE_SECOND_MAX 10
#define CON_WAKEUP_REMOTE_SECOND_DEAL 5

#if(CONFIG_METER_AREA_MODE_SOUTHGRID==CONFIG_METER_AREA_MODE)
#define CON_ALLLOSSVOLTAGE_SECOND_START 0
#define CON_ALLLOSSVOLTAGE_SECOND_DEAL  894
#define CON_ALLLOSSVOLTAGE_SECOND_MAX   (CON_ALLLOSSVOLTAGE_SECOND_DEAL+6)
#else
#define CON_ALLLOSSVOLTAGE_SECOND_START 500
#define CON_ALLLOSSVOLTAGE_SECOND_DEAL  558
#define CON_ALLLOSSVOLTAGE_SECOND_MAX   (CON_ALLLOSSVOLTAGE_SECOND_DEAL+2)
#endif

#if(CON_WAKEUP_REMOTE_SECOND_DEAL>=CON_WAKEUP_REMOTE_SECOND_MAX)
    DEFINEERR
#endif

#ifndef SW_LOWCOST
//AP_POWERDOWNWAKEUP_EXT uchar ucWakeUpOneDayCount;
//AP_POWERDOWNWAKEUP_EXT uchar ucWakeUpRemoteSecond;
#endif
AP_POWERDOWNWAKEUP_EXT u16 ucWakeUpRemoteTimeByMinute;
//AP_POWERDOWNWAKEUP_EXT u16 ucAllLossVoltageTimeByMinute;

AP_POWERDOWNWAKEUP_EXT uchar ucWakeUpHandSecondCount;


//AP_POWERDOWNWAKEUP_EXT u16 ucAllLossVoltageSecond;


AP_POWERDOWNWAKEUP_EXT u16 uiWakeUpAllTimes;


#if(CONFIG_METER_EVENT_COVEROPEN_SPECIAL_MODE_POWERDOWN_RECORD==CONFIG_METER_EVENT_COVEROPEN_SPECIAL_MODE)

AP_POWERDOWNWAKEUP_EXT void PowerDownOPenEEpromPower(void);

AP_POWERDOWNWAKEUP_EXT void PowerDownGetTime(void);

AP_POWERDOWNWAKEUP_EXT void PowerDownRecordEvent(void);

#endif













#endif  



