
//---------------------------------------------------------------
//--    可配置的数据内容定义起始-------------------
//---------------------------------------------------------------
#define GAL_NO          0
#define GAL_YES         1
#define GAL_UNKNOW      2
#define GAL_CLR         GAL_NO

#define BIT_VAR_ENABLE GAL_NO  

#define DEFINEERR   print("配置数据错误,请仔细检查!~~~~~~~~~");

//--AA 所支持的电表类型定义 AA--
//--AA 集中器内表 AA--
#define CONFIG_METER_TYPE_METER 0x9A

//--AA  通用多功能表，低成本方案, 25系列FLASH AA--
#define CONFIG_METER_TYPE_SD39F 0x4B

//--AA  低成本升级方案 模块表,2路485功能 AA--
#define CONFIG_METER_TYPE_SM39K 0x4C
//--AA  低成本升级方案 本地表,使用无线模块 ,25系列FLASH AA--
#define CONFIG_METER_TYPE_SM39L 0x4D
//--AA  低成本升级方案 载波表,使用载波模块 ,25系列FLASH AA--
#define CONFIG_METER_TYPE_SM39M 0x4E


//--AA  通用多功能表，硬件无改变,25系列FLASH AA--
#define CONFIG_METER_TYPE_SD39E 0x2B
//--AA  广东多功能表，增加不可更换载波模块AA--
#define CONFIG_METER_TYPE_SD39C 0x0C
//--AA  三相云南谐波表 AA--
#define CONFIG_METER_TYPE_SD39D 0x0D


//--AA  模块表,2路485功能 AA--
#define CONFIG_METER_TYPE_SM39H 0x3B
//--AA  无线表,使用无线模块 ,25系列FLASH AA--
#define CONFIG_METER_TYPE_SM39G 0x3C
//--AA  载波表,使用载波模块 ,25系列FLASH AA--
#define CONFIG_METER_TYPE_SM39I 0x3D
//--AA  江苏硬件表,2路485功能 ,25系列FLASH AA--
#define CONFIG_METER_TYPE_SM39F 0x3E
//--AA  江苏硬件表,无线模块 ,25系列FLASH AA--
#define CONFIG_METER_TYPE_SM39J 0x3F




// --AA 本地表与远程表的预定义AA--
//--AA 预付费模式:本地or 远程or 没有 AA--

//--AA  没有预付费功能 AA--
#define CONFIG_METER_PREPAY_MODE_DISABLE    0x00
//--AA 本地预付费方式 AA--
#define CONFIG_METER_PREPAY_MODE_LOCATION   0x01
//--AA 远程预付费方式 AA--
#define CONFIG_METER_PREPAY_MODE_FAR        0x02

//--AA 通讯介质定义:CPU,RF,NOHAVE,OTHER AA--
//--AA 使用虚拟的介质 AA--
#define CONFIG_METER_PREPAY_TYPE_DISABLE        0x00    
//--AA 使用CPU卡 AA--
#define CONFIG_METER_PREPAY_TYPE_CPUCARD    0x01
//--AA 使用射频卡 AA--
#define CONFIG_METER_PREPAY_TYPE_RFCARD     0x02
//--AA 使用其他类型的卡 AA--
#define CONFIG_METER_PREPAY_TYPE_OTHER      0x03


//--AA 控制继电器模式:内置or 外置or 没有 AA--
#define CONFIG_METER_RELAY_MODE_DISABLE     0x00
//--AA 控制继电器内置 AA--
#define CONFIG_METER_RELAY_MODE_INSIDE      0x01
//--AA 控制继电器外置 AA--
#define CONFIG_METER_RELAY_MODE_OUTSIDE     0x02

//--AA 辅助电源状态:辅助电源存在or 不存在 AA--
#define CONFIG_METER_AUX_MODE_DISABLE   GAL_NO
#define CONFIG_METER_AUX_MODE_ENABLE    GAL_YES

//--AA 第二路485工作方式:RS485 or 载波 or 无线模块 AA--
#define CONFIG_METER_NO2COMM_MODE_RS485 0x00
#define CONFIG_METER_NO2COMM_MODE_PLC       0x01
#define CONFIG_METER_NO2COMM_MODE_WIRELESS  0x02

//--AA 厂内生产程序状态配置 AA--
#define CONFIG_METER_FACTORY_MODE_DISABLE   GAL_NO
#define CONFIG_METER_FACTORY_MODE_ENABLE    GAL_YES

// --AA 阶梯电价是否存在AA--
#define CONFIG_METER_STEP_PERIODPRICE_MODE_DISABLE      GAL_NO
#define CONFIG_METER_STEP_PERIODPRICE_MODE_ENABLE       GAL_YES

// --AA 阶梯功能AA--
#define CONFIG_METER_STEP_MODE_DISABLE  GAL_NO
#define CONFIG_METER_STEP_MODE_ENABLE   GAL_YES

// --AA 停电显示功能 AA--
#define CONFIG_METER_POWERDOWN_DISPLAY_MODE_DISABLE  GAL_NO
#define CONFIG_METER_POWERDOWN_DISPLAY_MODE_ENABLE   GAL_YES

// --AA 脉冲尾数按费率记录功能 AA--
#define CONFIG_METER_POWERRESIDUE_PRICE_RECORD_MODE_DISABLE GAL_NO
#define CONFIG_METER_POWERRESIDUE_PRICE_RECORD_MODE_ENABLE  GAL_YES
// --AA 记录数据的FLASH格式方式AA--
// #define CONFIG_METER_FLASH_MODE_2_45DB321    0x00
// #define CONFIG_METER_FLASH_MODE_1_45DB161_1_45DB321  0x01


//--AA配置只有1片25系列FLASH。AA--
#define CONFIG_METER_FLASH_MODE_1_AT25FLASH     0x02
//--AA配置只有2片25系列FLASH。AA--
#define CONFIG_METER_FLASH_MODE_2_AT25FLASH     0x03



//--AA按键激活时，使用几个按键激活方式AA--
#define CONFIG_METER_WAKEUP_KEY_MODE_ONEKEY_UPKEY       0x01
#define CONFIG_METER_WAKEUP_KEY_MODE_ONEKEY_DOWNKEY     0x02
#define CONFIG_METER_WAKEUP_KEY_MODE_TWOKEY_ANY         0x03
//--AA按按键操作时,上下翻键功能是否反向AA--
//--AA即上翻键操作下翻动作，下翻键操作上翻动作AA--
#define CONFIG_METER_KEY_CHANGE_UP_DOWN_MODE_ENABLE GAL_YES
#define CONFIG_METER_KEY_CHANGE_UP_DOWN_MODE_DISABLE GAL_NO
//--AA事件判断时的延时时间定义AA--
//--AA山东版本最低判断延时为5秒AA--
#define CONFIG_METER_EVENT_DELAY_MIN_TIME_05 0x05
//--AA通用版本最低判断延时为10秒AA--
#define CONFIG_METER_EVENT_DELAY_MIN_TIME_10 0x0A




// --AA 带符号数的负号显示位置 AA--
#define CONFIG_METER_SIGNED_DIGIT_SHOW_MODE_FIXED   0x01    //显示位置固定
#define CONFIG_METER_SIGNED_DIGIT_SHOW_MODE_CLOSED  0X02    //显示位置靠近数字前面


#define CONFIG_METER_AREA_MODE_QUANGUO  0xC000
#define CONFIG_METER_AREA_MODE_JIANGSU  0xC250
#define CONFIG_METER_AREA_MODE_ZHEJIANG 0xC571
#define CONFIG_METER_AREA_MODE_ZHEJIANG_NINGBO      0x0574
#define CONFIG_METER_AREA_MODE_ZHEJIANG_HANGZHOU    0x0571
#define CONFIG_METER_AREA_MODE_SHANGHAI 0xC210
#define CONFIG_METER_AREA_MODE_JIANGXI  0xC791
#define CONFIG_METER_AREA_MODE_SICHUAN  0xC280
#define CONFIG_METER_AREA_MODE_HENAN    0xC371
#define CONFIG_METER_AREA_MODE_HUBEI    0x270
#define CONFIG_METER_AREA_MODE_GUANGDONG    0xC200
#define CONFIG_METER_AREA_MODE_QINGHAI  0xC971
#define CONFIG_METER_AREA_MODE_SHANDONG  0xC531
#define CONFIG_METER_AREA_MODE_HEBEI    0xC311
#define CONFIG_METER_AREA_MODE_HUABEI   0xB100

// 南网
#define CONFIG_METER_AREA_MODE_SOUTHGRID   0xB200

// --AA 显示模块中，显示电量时,高位的0是否显示 AA--
#define CONFIG_METER_DISPLAY_POWER_HIGHZERO_MODE_ENABLE GAL_YES
#define CONFIG_METER_DISPLAY_POWER_HIGHZERO_MODE_DISABLE GAL_NO

// --AA 停电时是否自动结束表盖开启端钮盖开启事件 AA--
#define CONFIG_METER_EVENT_COVEROPEN_SPECIAL_MODE_DISABLE 0x00
#define CONFIG_METER_EVENT_COVEROPEN_SPECIAL_MODE_POWERDOWN_NOSTOP 0x01
#define CONFIG_METER_EVENT_COVEROPEN_SPECIAL_MODE_POWERDOWN_RECORD 0x02


// --AA 控制继电器自动合闸方式 AA--
#define CONFIG_METER_RELAY_AUTOCLOSE_MODE_ENABLE    GAL_YES
#define CONFIG_METER_RELAY_AUTOCLOSE_MODE_DISABLE   GAL_NO

// --AA 远程表 保电解除后是否恢复原先状态 AA--
#define CONFIG_METER_RELAY_FAR_PROTECT_CARRYOUT_MODE_ENABLE GAL_YES
#define CONFIG_METER_RELAY_FAR_PROTECT_CARRYOUT_MODE_DISABLE    GAL_NO

// --AA 25系列flash
#define FLASH_ATMEL         1   //
#define FLASH_WIBOND        2   // 华邦
#define FLASH_ST            3   // st

//---------------------------------------------------------------
//--    可配置的数据内容定义结束-------------------
//---------------------------------------------------------------
//#define CONFIG_METER_REMOTE_INPUT_ENABLE   GAL_YES


//为了节省电池，在上电时结束事件
#define CONFIG_METER_STOPEVENT_POWERON  GAL_NO
//---------------------------------------------------------------
//--    可配置的数据起始-------------------
//---------------------------------------------------------------
#define CONFIG_METER_SW_DEBUG_MODE  GAL_NO         //调试程序开关、正式release时需要关闭
#if(CONFIG_METER_SW_DEBUG_MODE == GAL_YES)
    #define MEM_ERR_RECORD_ENABLE   GAL_YES         //存取器错误记录
    #define DISPLAY_PRINT_ENABLE    GAL_NO         //显示打印特性使能
    #define POWER_SW_DEBUG_ENABLE   GAL_NO         //电源开关虚拟软件调试
#else
    #define MEM_ERR_RECORD_ENABLE   GAL_NO
    #define DISPLAY_PRINT_ENABLE    GAL_NO
    #define POWER_SW_DEBUG_ENABLE   GAL_NO
#endif

#define FILE_BUFF_ENABLE            GAL_YES         //文件读写缓冲使能

#ifdef FACTORY_MODE_ENABLE
#define CONFIG_METER_FACTORY_MODE       CONFIG_METER_FACTORY_MODE_ENABLE
#define CONFIG_METER_HARMONIC_ENABLE    GAL_NO      //谐波功能使能
#else
#define CONFIG_METER_FACTORY_MODE       CONFIG_METER_FACTORY_MODE_DISABLE
#define CONFIG_METER_HARMONIC_ENABLE    GAL_YES      //谐波功能使能
#endif

#define CONFIG_METER_AREA_MODE CONFIG_METER_AREA_MODE_QUANGUO
#if 0
      SM39K 1级三相费控智能电能表（远程/开关内置）； 220v  10（40）A   5只   
      SM39K 1级三相费控智能电能表（CPU卡/开关内置）； 220v  10（40）A   5只
      SM39L 1级三相费控智能电能表(无线/远程/开关内置）； 220v  10（40）A   10只
      SM39L  0.5S级三相费控智能电能表(无线/远程/开关外置） 57  1.5（6）A   10只
#endif

// --AA 电表类型AA--
#define CONFIG_METER_TYPE CONFIG_METER_TYPE_METER
// --AA 预付费模式AA--
#define CONFIG_METER_PREPAY_MODE CONFIG_METER_PREPAY_MODE_DISABLE
#define CONFIG_METER_PREPAY_TYPE CONFIG_METER_PREPAY_TYPE_DISABLE
// --AA 电表继电器控制方式AA--
#define CONFIG_METER_RELAY_MODE     CONFIG_METER_RELAY_MODE_DISABLE
// --AA 电表辅助电源是否存在AA--
#define CONFIG_METER_AUX_MODE   CONFIG_METER_AUX_MODE_DISABLE

// --AA 阶梯电价是否存在----该配置选项使用自动配置功能AA--
// #define CONFIG_METER_STEP_PERIODPRICE_MODE CONFIG_METER_STEP_PERIODPRICE_MODE_ENABLE


// --AA 记录FLASH模式 AA--
#define CONFIG_METER_FLASH_MODE CONFIG_METER_FLASH_MODE_1_AT25FLASH


// --AA 程序软件版本号是否存在AA--
#define CONFIG_METER_SOFT_VER_ENABLE GAL_YES

#define CONFIG_METER_EVENT_LASTTIME_SAVEMODE    GAL_NO

#define FLASH_COR       FLASH_WIBOND

//是否是多功能表，SD39B,SD39E,SD39F都是
#if((CONFIG_METER_TYPE_SD39F==CONFIG_METER_TYPE) || (CONFIG_METER_TYPE_SD39E==CONFIG_METER_TYPE) || (CONFIG_METER_TYPE_METER==CONFIG_METER_TYPE))
#define CONFIG_METER_MULTI_FUNCTION     GAL_YES
#else
#define CONFIG_METER_MULTI_FUNCTION     GAL_NO
#endif
//---------------------------------------------------------------
//--    可配置的数据结束-------------------
//---------------------------------------------------------------


//---------------------------------------------------------------
//--    以下是由配置数据产生的配置数据以及数据---
//--    如果没有特殊情况，请勿更改---
//---------------------------------------------------------------
#if((CONFIG_METER_TYPE_SM39F==CONFIG_METER_TYPE) || (CONFIG_METER_TYPE_SM39J==CONFIG_METER_TYPE))
    #define CON_CELL_IS_6V  GAL_YES
#else
    #define CON_CELL_IS_6V  GAL_NO
#endif

#if((CONFIG_METER_TYPE_SD39E==CONFIG_METER_TYPE) || (CONFIG_METER_TYPE_SD39F==CONFIG_METER_TYPE) || (CONFIG_METER_TYPE_METER==CONFIG_METER_TYPE))
// --AA 双485表表 AA--
    #define CONFIG_METER_NO2COMM_MODE CONFIG_METER_NO2COMM_MODE_RS485
#elif(CONFIG_METER_TYPE_SD39C==CONFIG_METER_TYPE)
// --AA 双485表表 AA--
    #define CONFIG_METER_NO2COMM_MODE CONFIG_METER_NO2COMM_MODE_PLC
#elif(CONFIG_METER_TYPE_SM39H==CONFIG_METER_TYPE)
// --AA 双485表表 AA--
    #define CONFIG_METER_NO2COMM_MODE CONFIG_METER_NO2COMM_MODE_RS485
#elif(CONFIG_METER_TYPE_SM39G==CONFIG_METER_TYPE)
// --AA 无线表 AA--
    #define CONFIG_METER_NO2COMM_MODE CONFIG_METER_NO2COMM_MODE_WIRELESS
#elif(CONFIG_METER_TYPE_SM39I==CONFIG_METER_TYPE)
// --AA 载波表 AA--
    #define CONFIG_METER_NO2COMM_MODE CONFIG_METER_NO2COMM_MODE_PLC
#elif(CONFIG_METER_TYPE_SM39F==CONFIG_METER_TYPE)
// --AA 江苏双485表 AA--
    #define CONFIG_METER_NO2COMM_MODE CONFIG_METER_NO2COMM_MODE_RS485
#elif(CONFIG_METER_TYPE_SM39J==CONFIG_METER_TYPE)
// --AA 江苏 无线表  AA--
    #define CONFIG_METER_NO2COMM_MODE CONFIG_METER_NO2COMM_MODE_WIRELESS
#elif(CONFIG_METER_TYPE_SM39K==CONFIG_METER_TYPE)
//--AA  低成本升级方案 模块表,2路485功能 AA--
    #define CONFIG_METER_NO2COMM_MODE CONFIG_METER_NO2COMM_MODE_RS485
#elif(CONFIG_METER_TYPE_SM39L==CONFIG_METER_TYPE)
//--AA  低成本升级方案 无线表,使用无线模块 ,25系列FLASH AA--
    #define CONFIG_METER_NO2COMM_MODE CONFIG_METER_NO2COMM_MODE_WIRELESS
#elif(CONFIG_METER_TYPE_SM39M==CONFIG_METER_TYPE)
//--AA  低成本升级方案 载波表,使用载波模块 ,25系列FLASH AA--
    #define CONFIG_METER_NO2COMM_MODE CONFIG_METER_NO2COMM_MODE_PLC
#else
    DEFINEERR
#endif

#if(CONFIG_METER_AREA_MODE_ZHEJIANG_NINGBO==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_DISPLAY_POWER_HIGHZERO_MODE CONFIG_METER_DISPLAY_POWER_HIGHZERO_MODE_ENABLE
#endif
#if(CONFIG_METER_AREA_MODE_HENAN==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_DISPLAY_POWER_HIGHZERO_MODE CONFIG_METER_DISPLAY_POWER_HIGHZERO_MODE_ENABLE
#endif

// --AA 阶梯电价是否存在AA--
#if (CONFIG_METER_PREPAY_MODE==CONFIG_METER_PREPAY_MODE_LOCATION)
    #define CONFIG_METER_STEP_PERIODPRICE_MODE CONFIG_METER_STEP_PERIODPRICE_MODE_ENABLE
    #define CONFIG_METER_STEP_MODE CONFIG_METER_STEP_MODE_ENABLE
#else
    #if((CONFIG_METER_TYPE_SM39F==CONFIG_METER_TYPE)||(CONFIG_METER_TYPE_SM39J==CONFIG_METER_TYPE))
        #define CONFIG_METER_STEP_MODE CONFIG_METER_STEP_MODE_ENABLE
    #else
        #define CONFIG_METER_STEP_MODE CONFIG_METER_STEP_MODE_DISABLE
    #endif
    #define CONFIG_METER_STEP_PERIODPRICE_MODE CONFIG_METER_STEP_PERIODPRICE_MODE_DISABLE
#endif

// --AA 表盖开启特殊方式 AA--
#if(CONFIG_METER_AREA_MODE_ZHEJIANG==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_EVENT_COVEROPEN_SPECIAL_MODE CONFIG_METER_EVENT_COVEROPEN_SPECIAL_MODE_POWERDOWN_NOSTOP
#endif
#if(CONFIG_METER_AREA_MODE_ZHEJIANG_NINGBO==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_EVENT_COVEROPEN_SPECIAL_MODE CONFIG_METER_EVENT_COVEROPEN_SPECIAL_MODE_POWERDOWN_NOSTOP
#endif
#if(CONFIG_METER_AREA_MODE_ZHEJIANG_HANGZHOU==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_EVENT_COVEROPEN_SPECIAL_MODE CONFIG_METER_EVENT_COVEROPEN_SPECIAL_MODE_POWERDOWN_NOSTOP
#endif
#if(CONFIG_METER_AREA_MODE_SHANDONG==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_EVENT_COVEROPEN_SPECIAL_MODE CONFIG_METER_EVENT_COVEROPEN_SPECIAL_MODE_POWERDOWN_RECORD
#endif

// --AA 远程预付费表 外置继电器自动合闸方式 AA--
#if(CONFIG_METER_RELAY_MODE==CONFIG_METER_RELAY_MODE_OUTSIDE)
    #if(CONFIG_METER_AREA_MODE_ZHEJIANG==CONFIG_METER_AREA_MODE)
        #define CONFIG_METER_RELAY_AUTOCLOSE_MODE CONFIG_METER_RELAY_AUTOCLOSE_MODE_ENABLE
    #endif
    #if(CONFIG_METER_AREA_MODE_ZHEJIANG_NINGBO==CONFIG_METER_AREA_MODE)
        #define CONFIG_METER_RELAY_AUTOCLOSE_MODE CONFIG_METER_RELAY_AUTOCLOSE_MODE_ENABLE
    #endif
    #if(CONFIG_METER_AREA_MODE_ZHEJIANG_HANGZHOU==CONFIG_METER_AREA_MODE)
        #define CONFIG_METER_RELAY_AUTOCLOSE_MODE CONFIG_METER_RELAY_AUTOCLOSE_MODE_ENABLE
    #endif
#endif

#if((CONFIG_METER_TYPE_SM39F==CONFIG_METER_TYPE)||(CONFIG_METER_TYPE_SM39J==CONFIG_METER_TYPE))
    #define CONFIG_METER_RELAY_AUTOCLOSE_MODE CONFIG_METER_RELAY_AUTOCLOSE_MODE_ENABLE
#endif

#if(CONFIG_METER_AREA_MODE_SHANDONG==CONFIG_METER_AREA_MODE)
    #if(CONFIG_METER_RELAY_MODE==CONFIG_METER_RELAY_MODE_OUTSIDE)
// --AA 山东的要求继电器外置的表，自动合闸 AA--
        #define CONFIG_METER_RELAY_AUTOCLOSE_MODE CONFIG_METER_RELAY_AUTOCLOSE_MODE_ENABLE
    #endif
#endif

// --AA 远程表 保电解除后是否恢复原先状态 AA--
//#if(CONFIG_METER_RELAY_MODE==CONFIG_METER_RELAY_MODE_OUTSIDE)
    //确认浙江版本这个需求不依赖于继电器内外置类型
    #if(CONFIG_METER_AREA_MODE_ZHEJIANG==CONFIG_METER_AREA_MODE)
        #define CONFIG_METER_RELAY_FAR_PROTECT_CARRYOUT_MODE CONFIG_METER_RELAY_FAR_PROTECT_CARRYOUT_MODE_ENABLE
    #endif
    #if(CONFIG_METER_AREA_MODE_ZHEJIANG_NINGBO==CONFIG_METER_AREA_MODE)
        #define CONFIG_METER_RELAY_FAR_PROTECT_CARRYOUT_MODE CONFIG_METER_RELAY_FAR_PROTECT_CARRYOUT_MODE_ENABLE
    #endif
    #if(CONFIG_METER_AREA_MODE_ZHEJIANG_HANGZHOU==CONFIG_METER_AREA_MODE)
        #define CONFIG_METER_RELAY_FAR_PROTECT_CARRYOUT_MODE CONFIG_METER_RELAY_FAR_PROTECT_CARRYOUT_MODE_ENABLE
    #endif
//#endif


// --AA 停电显示功能 AA--
#if((CONFIG_METER_AREA_MODE_GUANGDONG==CONFIG_METER_AREA_MODE))
#define CONFIG_METER_POWERDOWN_DISPLAY_MODE CONFIG_METER_POWERDOWN_DISPLAY_MODE_ENABLE
#else
#define CONFIG_METER_POWERDOWN_DISPLAY_MODE CONFIG_METER_POWERDOWN_DISPLAY_MODE_DISABLE
#endif
#if(CONFIG_METER_AREA_MODE_SHANDONG==CONFIG_METER_AREA_MODE)
// --AA 脉冲尾数按费率记录功能 AA--
#define CONFIG_METER_POWERRESIDUE_PRICE_RECORD_MODE     CONFIG_METER_POWERRESIDUE_PRICE_RECORD_MODE_ENABLE
#endif

#if((CONFIG_METER_AREA_MODE_HEBEI==CONFIG_METER_AREA_MODE) || (CONFIG_METER_AREA_MODE_HUABEI==CONFIG_METER_AREA_MODE))
// --AA 带符号数的负号显示位置 AA--
#define CONFIG_METER_SIGNED_DIGIT_SHOW_MODE CONFIG_METER_SIGNED_DIGIT_SHOW_MODE_CLOSED
#endif

#if((CONFIG_METER_TYPE_SM39F==CONFIG_METER_TYPE)||(CONFIG_METER_TYPE_SM39J==CONFIG_METER_TYPE))
#define CONFIG_METER_KEY_CHANGE_UP_DOWN_MODE CONFIG_METER_KEY_CHANGE_UP_DOWN_MODE_ENABLE
#endif

#if(CONFIG_METER_AREA_MODE_SHANDONG==CONFIG_METER_AREA_MODE)
#define CONFIG_METER_KEY_CHANGE_UP_DOWN_MODE CONFIG_METER_KEY_CHANGE_UP_DOWN_MODE_ENABLE
#endif

#if(CONFIG_METER_AREA_MODE_SHANDONG==CONFIG_METER_AREA_MODE)
#define CONFIG_METER_KEY_CHANGE_UP_DOWN_MODE CONFIG_METER_KEY_CHANGE_UP_DOWN_MODE_ENABLE
#endif

// --AA 按键激活 时，需要几个按键设定 AA--
#if(CONFIG_METER_AREA_MODE_SHANDONG==CONFIG_METER_AREA_MODE)
#define CONFIG_METER_EVENT_DELAY_MIN_TIME CONFIG_METER_EVENT_DELAY_MIN_TIME_05
#endif
// #if(CONFIG_METER_RELAY_MODE_DISABLE ==CONFIG_METER_RELAY_MODE)
    #define CONFIG_METER_RELAY_CHECK_BY_CURRENT GAL_NO
// #else
//  #define CONFIG_METER_RELAY_CHECK_BY_CURRENT GAL_YES
// #endif
#if(CONFIG_METER_AREA_MODE_QUANGUO==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA_A '0'
    #define CONFIG_METER_AREA_DATA_B '0'
    #define CONFIG_METER_AREA_DATA_C '1'
    #define CONFIG_METER_AREA_DATA_D 'A'
#endif
#if(CONFIG_METER_AREA_MODE_JIANGSU==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA_A '0'
    #define CONFIG_METER_AREA_DATA_B '5'
    #define CONFIG_METER_AREA_DATA_C '2'
    #define CONFIG_METER_AREA_DATA_D 'C'
#endif
#if(CONFIG_METER_AREA_MODE_ZHEJIANG==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA_A '1'
    #define CONFIG_METER_AREA_DATA_B '7'
    #define CONFIG_METER_AREA_DATA_C '5'
    #define CONFIG_METER_AREA_DATA_D 'C'
#endif

#if(CONFIG_METER_AREA_MODE_ZHEJIANG_NINGBO==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA_A '4'
    #define CONFIG_METER_AREA_DATA_B '7'
    #define CONFIG_METER_AREA_DATA_C '5'
    #define CONFIG_METER_AREA_DATA_D '0'
#endif

#if(CONFIG_METER_AREA_MODE_ZHEJIANG_HANGZHOU==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA_A '1'
    #define CONFIG_METER_AREA_DATA_B '7'
    #define CONFIG_METER_AREA_DATA_C '5'
    #define CONFIG_METER_AREA_DATA_D '0'
#endif



#if(CONFIG_METER_AREA_MODE_SHANGHAI==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA_A '0'
    #define CONFIG_METER_AREA_DATA_B '1'
    #define CONFIG_METER_AREA_DATA_C '2'
    #define CONFIG_METER_AREA_DATA_D 'C'
#endif


#if(CONFIG_METER_AREA_MODE_SICHUAN==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA_A '0'
    #define CONFIG_METER_AREA_DATA_B '8'
    #define CONFIG_METER_AREA_DATA_C '2'
    #define CONFIG_METER_AREA_DATA_D 'C'
#endif

#if(CONFIG_METER_AREA_MODE_JIANGXI==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA_A '1'
    #define CONFIG_METER_AREA_DATA_B '9'
    #define CONFIG_METER_AREA_DATA_C '7'
    #define CONFIG_METER_AREA_DATA_D 'C'
#endif

#if(CONFIG_METER_AREA_MODE_HENAN==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA_A '1'
    #define CONFIG_METER_AREA_DATA_B '7'
    #define CONFIG_METER_AREA_DATA_C '3'
    #define CONFIG_METER_AREA_DATA_D 'C'
#endif


#if(CONFIG_METER_AREA_MODE_HUBEI==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA_A '0'
    #define CONFIG_METER_AREA_DATA_B '7'
    #define CONFIG_METER_AREA_DATA_C '2'
    #define CONFIG_METER_AREA_DATA_D 'C'
#endif

#if(CONFIG_METER_AREA_MODE_GUANGDONG==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA_A '0'
    #define CONFIG_METER_AREA_DATA_B '0'
    #define CONFIG_METER_AREA_DATA_C '2'
    #define CONFIG_METER_AREA_DATA_D 'C'
#endif

#if(CONFIG_METER_AREA_MODE_QINGHAI==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA_A '1'
    #define CONFIG_METER_AREA_DATA_B '7'
    #define CONFIG_METER_AREA_DATA_C '9'
    #define CONFIG_METER_AREA_DATA_D 'C'
#endif

#if(CONFIG_METER_AREA_MODE_SHANDONG==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA_A '1'
    #define CONFIG_METER_AREA_DATA_B '3'
    #define CONFIG_METER_AREA_DATA_C '5'
    #define CONFIG_METER_AREA_DATA_D 'C'
#endif

#if(CONFIG_METER_AREA_MODE_HEBEI==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA_A '1'
    #define CONFIG_METER_AREA_DATA_B '1'
    #define CONFIG_METER_AREA_DATA_C '3'
    #define CONFIG_METER_AREA_DATA_D 'C'
#endif

#if(CONFIG_METER_AREA_MODE_HUABEI==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA_A '0'
    #define CONFIG_METER_AREA_DATA_B '0'
    #define CONFIG_METER_AREA_DATA_C '1'
    #define CONFIG_METER_AREA_DATA_D 'B'
#endif

#if(CONFIG_METER_AREA_MODE_SOUTHGRID==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA_A '0'
    #define CONFIG_METER_AREA_DATA_B '0'
    #define CONFIG_METER_AREA_DATA_C '2'
    #define CONFIG_METER_AREA_DATA_D 'B'
#endif


#if(CONFIG_METER_TYPE_SM39H==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER_A 'H'
    #define CONFIG_METER_SOFT_VER_B '9'
    #define CONFIG_METER_SOFT_VER_C '3'
    #define CONFIG_METER_SOFT_VER_D 'M'
    #define CONFIG_METER_SOFT_VER_E 'S' 
#endif
#if(CONFIG_METER_TYPE_SM39G==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER_A 'G'
    #define CONFIG_METER_SOFT_VER_B '9'
    #define CONFIG_METER_SOFT_VER_C '3'
    #define CONFIG_METER_SOFT_VER_D 'M'
    #define CONFIG_METER_SOFT_VER_E 'S' 
#endif
#if(CONFIG_METER_TYPE_SM39I==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER_A 'I'
    #define CONFIG_METER_SOFT_VER_B '9'
    #define CONFIG_METER_SOFT_VER_C '3'
    #define CONFIG_METER_SOFT_VER_D 'M'
    #define CONFIG_METER_SOFT_VER_E 'S' 
#endif
#if(CONFIG_METER_TYPE_SM39F==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER_A 'F'
    #define CONFIG_METER_SOFT_VER_B '9'
    #define CONFIG_METER_SOFT_VER_C '3'
    #define CONFIG_METER_SOFT_VER_D 'M'
    #define CONFIG_METER_SOFT_VER_E 'S' 
#endif
#if(CONFIG_METER_TYPE_SM39J==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER_A 'J'
    #define CONFIG_METER_SOFT_VER_B '9'
    #define CONFIG_METER_SOFT_VER_C '3'
    #define CONFIG_METER_SOFT_VER_D 'M'
    #define CONFIG_METER_SOFT_VER_E 'S' 
#endif
#if(CONFIG_METER_TYPE_SD39E==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER_A 'E'
    #define CONFIG_METER_SOFT_VER_B '9'
    #define CONFIG_METER_SOFT_VER_C '3'
    #define CONFIG_METER_SOFT_VER_D 'D'
    #define CONFIG_METER_SOFT_VER_E 'S' 
#endif
#if(CONFIG_METER_TYPE_SD39F==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER_A 'F'
    #define CONFIG_METER_SOFT_VER_B '9'
    #define CONFIG_METER_SOFT_VER_C '3'
    #define CONFIG_METER_SOFT_VER_D 'D'
    #define CONFIG_METER_SOFT_VER_E 'S' 
#endif
#if(CONFIG_METER_TYPE_SD39C==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER_A 'C'
    #define CONFIG_METER_SOFT_VER_B '9'
    #define CONFIG_METER_SOFT_VER_C '3'
    #define CONFIG_METER_SOFT_VER_D 'D'
    #define CONFIG_METER_SOFT_VER_E 'S' 
#endif

#if(CONFIG_METER_TYPE_SM39K==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER_A 'K'
    #define CONFIG_METER_SOFT_VER_B '9'
    #define CONFIG_METER_SOFT_VER_C '3'
    #define CONFIG_METER_SOFT_VER_D 'M'
    #define CONFIG_METER_SOFT_VER_E 'S' 
#endif
#if(CONFIG_METER_TYPE_SM39L==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER_A 'L'
    #define CONFIG_METER_SOFT_VER_B '9'
    #define CONFIG_METER_SOFT_VER_C '3'
    #define CONFIG_METER_SOFT_VER_D 'M'
    #define CONFIG_METER_SOFT_VER_E 'S' 
#endif
#if(CONFIG_METER_TYPE_SM39M==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER_A 'M'
    #define CONFIG_METER_SOFT_VER_B '9'
    #define CONFIG_METER_SOFT_VER_C '3'
    #define CONFIG_METER_SOFT_VER_D 'M'
    #define CONFIG_METER_SOFT_VER_E 'S' 
#endif
#if(CONFIG_METER_TYPE_METER==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER_A 'R'
    #define CONFIG_METER_SOFT_VER_B 'E'
    #define CONFIG_METER_SOFT_VER_C 'T'
    #define CONFIG_METER_SOFT_VER_D 'E'
    #define CONFIG_METER_SOFT_VER_E 'M' 
#endif

#if((CONFIG_METER_TYPE==CONFIG_METER_TYPE_SM39H)||(CONFIG_METER_TYPE==CONFIG_METER_TYPE_SM39G)||(CONFIG_METER_TYPE==CONFIG_METER_TYPE_SM39I)||(CONFIG_METER_TYPE==CONFIG_METER_TYPE_SM39F)||(CONFIG_METER_TYPE_SM39J==CONFIG_METER_TYPE)||(CONFIG_METER_TYPE_SM39K==CONFIG_METER_TYPE)||(CONFIG_METER_TYPE_SM39L==CONFIG_METER_TYPE)||(CONFIG_METER_TYPE_SM39M==CONFIG_METER_TYPE))
    #if(CONFIG_METER_PREPAY_MODE == CONFIG_METER_PREPAY_MODE_LOCATION)
        #if(CONFIG_METER_RELAY_MODE == CONFIG_METER_RELAY_MODE_INSIDE)
            #define CONFIG_METER_SOFT_VER_V 'C'
        #endif
    #endif
    #if(CONFIG_METER_PREPAY_MODE == CONFIG_METER_PREPAY_MODE_LOCATION)
        #if(CONFIG_METER_RELAY_MODE == CONFIG_METER_RELAY_MODE_OUTSIDE)
            #define CONFIG_METER_SOFT_VER_V 'D'
        #endif
    #endif

    #if(CONFIG_METER_PREPAY_MODE == CONFIG_METER_PREPAY_MODE_FAR)
        #if(CONFIG_METER_RELAY_MODE == CONFIG_METER_RELAY_MODE_INSIDE)
            #define CONFIG_METER_SOFT_VER_V 'E'
        #endif
    #endif
    #if(CONFIG_METER_PREPAY_MODE == CONFIG_METER_PREPAY_MODE_FAR)
        #if(CONFIG_METER_RELAY_MODE == CONFIG_METER_RELAY_MODE_OUTSIDE)
            #define CONFIG_METER_SOFT_VER_V 'F'
        #endif
    #endif
#elif((GAL_YES == CONFIG_METER_MULTI_FUNCTION)||(CONFIG_METER_TYPE_SD39C==CONFIG_METER_TYPE))
    #if(CONFIG_METER_AUX_MODE==CONFIG_METER_AUX_MODE_ENABLE)
        #define CONFIG_METER_SOFT_VER_V 'A'
    #endif
    #if(CONFIG_METER_AUX_MODE==CONFIG_METER_AUX_MODE_DISABLE)
        #define CONFIG_METER_SOFT_VER_V 'B'
    #endif
#else
        #define CONFIG_METER_SOFT_VER_V 'V'
#endif

//---------------------------------------------------------------
//--    以下是对配置数据进行验证-------------------
//--    如果没有特殊情况，请勿更改----------------
//---------------------------------------------------------------
//----AA 第2路485工作模式是否已经定义AA----
#ifndef CONFIG_METER_NO2COMM_MODE
    DEFINEERR
#endif

//----AA 程序版本是否已经定义AA----
#ifndef CONFIG_METER_SOFT_VER_A
    DEFINEERR
#endif
#ifndef CONFIG_METER_SOFT_VER_B
    DEFINEERR
#endif
#ifndef CONFIG_METER_SOFT_VER_C
    DEFINEERR
#endif
#ifndef CONFIG_METER_SOFT_VER_D
    DEFINEERR
#endif

#ifndef CONFIG_METER_SOFT_VER_V
    DEFINEERR
#endif
//----AA 程序区域版本是否已经定义AA----
#ifndef CONFIG_METER_AREA_DATA_A
    DEFINEERR
#endif
#ifndef CONFIG_METER_AREA_DATA_B
    DEFINEERR
#endif
#ifndef CONFIG_METER_AREA_DATA_C
    DEFINEERR
#endif
#ifndef CONFIG_METER_AREA_DATA_D
    DEFINEERR
#endif

#ifndef CONFIG_METER_DISPLAY_POWER_HIGHZERO_MODE
    #define CONFIG_METER_DISPLAY_POWER_HIGHZERO_MODE CONFIG_METER_DISPLAY_POWER_HIGHZERO_MODE_DISABLE
#endif
#ifndef CONFIG_METER_EVENT_COVEROPEN_SPECIAL_MODE
    #define CONFIG_METER_EVENT_COVEROPEN_SPECIAL_MODE CONFIG_METER_EVENT_COVEROPEN_SPECIAL_MODE_DISABLE
#endif

#ifndef CONFIG_METER_RELAY_AUTOCLOSE_MODE
    #define CONFIG_METER_RELAY_AUTOCLOSE_MODE CONFIG_METER_RELAY_AUTOCLOSE_MODE_DISABLE
#endif
#ifndef CONFIG_METER_RELAY_FAR_PROTECT_CARRYOUT_MODE
    #define CONFIG_METER_RELAY_FAR_PROTECT_CARRYOUT_MODE CONFIG_METER_RELAY_FAR_PROTECT_CARRYOUT_MODE_DISABLE
#endif


#ifndef CONFIG_METER_WAKEUP_KEY_MODE
    #define CONFIG_METER_WAKEUP_KEY_MODE CONFIG_METER_WAKEUP_KEY_MODE_ONEKEY_UPKEY
#endif


#ifndef CONFIG_METER_KEY_CHANGE_UP_DOWN_MODE
    #define CONFIG_METER_KEY_CHANGE_UP_DOWN_MODE CONFIG_METER_KEY_CHANGE_UP_DOWN_MODE_DISABLE
#endif


#ifndef CONFIG_METER_POWERRESIDUE_PRICE_RECORD_MODE
    #define CONFIG_METER_POWERRESIDUE_PRICE_RECORD_MODE CONFIG_METER_POWERRESIDUE_PRICE_RECORD_MODE_DISABLE
#endif
#ifndef CONFIG_METER_SIGNED_DIGIT_SHOW_MODE
    // --AA 带符号数的负号显示位置 AA--
    #define CONFIG_METER_SIGNED_DIGIT_SHOW_MODE CONFIG_METER_SIGNED_DIGIT_SHOW_MODE_FIXED
#endif

#ifndef CONFIG_METER_EVENT_DELAY_MIN_TIME
    #define CONFIG_METER_EVENT_DELAY_MIN_TIME CONFIG_METER_EVENT_DELAY_MIN_TIME_10
#endif

// --AA     AA--
#if ((GAL_YES == CONFIG_METER_MULTI_FUNCTION)||(CONFIG_METER_TYPE==CONFIG_METER_TYPE_SD39C))
    // --AA  SD39B表应该没有预付费功能   AA--
    #if(CONFIG_METER_PREPAY_MODE!=CONFIG_METER_PREPAY_MODE_DISABLE)
        DEFINEERR
    #endif
    #if(CONFIG_METER_PREPAY_TYPE!=CONFIG_METER_PREPAY_TYPE_DISABLE)
        DEFINEERR
    #endif
    // --AA  SD39B表应该没有继电器控制功能   AA--
    #if(CONFIG_METER_RELAY_MODE !=CONFIG_METER_RELAY_MODE_DISABLE)
        DEFINEERR
    #endif
#endif

#if ((CONFIG_METER_TYPE==CONFIG_METER_TYPE_SM39H)||(CONFIG_METER_TYPE==CONFIG_METER_TYPE_SM39G)||(CONFIG_METER_TYPE==CONFIG_METER_TYPE_SM39I)||(CONFIG_METER_TYPE==CONFIG_METER_TYPE_SM39F)||(CONFIG_METER_TYPE_SM39J==CONFIG_METER_TYPE)||(CONFIG_METER_TYPE_SM39K==CONFIG_METER_TYPE)||(CONFIG_METER_TYPE_SM39L==CONFIG_METER_TYPE)||(CONFIG_METER_TYPE_SM39M==CONFIG_METER_TYPE))
    // --AA  SM39B/C/D/E表没有辅助电源   AA--
    #if(CONFIG_METER_AUX_MODE !=CONFIG_METER_AUX_MODE_DISABLE)
        DEFINEERR
    #endif
#endif

#if(CONFIG_METER_PREPAY_MODE ==CONFIG_METER_PREPAY_MODE_DISABLE)
    // --AA  没有预付费功能的表，没有继电器功能   AA--
    #if(CONFIG_METER_RELAY_MODE !=CONFIG_METER_RELAY_MODE_DISABLE)
        DEFINEERR
    #endif
#endif
#if(CONFIG_METER_PREPAY_MODE !=CONFIG_METER_PREPAY_MODE_DISABLE)
    // --AA  如果是预付费表，则电表必须要有继电器  AA--
    #if(CONFIG_METER_RELAY_MODE ==CONFIG_METER_RELAY_MODE_DISABLE)
        DEFINEERR
    #endif
#endif


#if(CONFIG_METER_PREPAY_MODE ==CONFIG_METER_PREPAY_MODE_FAR)
    // --AA  如果远程表，则必须是虚拟介质，不能使用其他类型的卡   AA--
    #if(CONFIG_METER_PREPAY_TYPE!=CONFIG_METER_PREPAY_TYPE_DISABLE)
        DEFINEERR
    #endif
#endif
#if(CONFIG_METER_PREPAY_MODE !=CONFIG_METER_PREPAY_MODE_LOCATION)
    // --AA  只有本地费控表，才有阶梯功能 AA--
    #if(CONFIG_METER_STEP_PERIODPRICE_MODE==CONFIG_METER_STEP_PERIODPRICE_MODE_ENABLE)
        DEFINEERR
    #endif
#endif


#if(CONFIG_METER_STEP_MODE!=CONFIG_METER_STEP_MODE_ENABLE)
    // --AA 只有在有阶梯功能的表中，才有阶梯费率 AA--
    #if(CONFIG_METER_STEP_PERIODPRICE_MODE_ENABLE==CONFIG_METER_STEP_PERIODPRICE_MODE)
        DEFINEERR
    #endif
#endif

#if(CONFIG_METER_TYPE_SD39C==CONFIG_METER_TYPE)
//--AA本硬件暂时还不支持该型号。AA-------
        DEFINEERR
#endif

#if(CONFIG_METER_TYPE_SD39D==CONFIG_METER_TYPE)
//--AA本硬件暂时还不支持该型号。AA-------
        DEFINEERR
#endif

#if(CONFIG_METER_AREA_MODE_SHANDONG == CONFIG_METER_AREA_MODE)
//--AA山东需求需要2片25FLASH    AA-------
    #if(CONFIG_METER_FLASH_MODE_2_AT25FLASH != CONFIG_METER_FLASH_MODE)
        DEFINEERR
    #endif
#endif

