#ifndef __GOL_VERSION_C__
#define __GOL_VERSION_C__

#include "common.h"

//#define makechar(x)     #@x 
#define MAKE_STR(x)                 #x
#if 1   
//__GNU_C__
#define STR_LINK2(A,B)              (A B)
#define STR_LINK3(S1,S2,S3)         (S1 S2 S3)
#define STR_LINK4(S1,S2,S3,S4)      (S1 S2 S3 S4)
#define STR_LINK5(S1,S2,S3,S4,S5)   (S1 S2 S3 S4 S5)
#define STR_LINK10(S1,S2,S3,S4,S5,S6,S7,S8,S9,S10)  (S1 S2 S3 S4 S5 S6 S7 S8 S9 S10)
#else
//__IAR_C__
#define STR_LINK2(A,B)              A##""##B
#define STR_LINK3(S1,S2,S3)         S1##""##S2##""##S3
#define STR_LINK4(S1,S2,S3,S4)      S1##""##S2##""##S3##""##S4
#define STR_LINK5(S1,S2,S3,S4,S5)   S1##""##S2##""##S3##""##S4##""##S5
#define STR_LINK10(S1,S2,S3,S4,S5,S6,S7,S8,S9,S10)  S1##""##S2##""##S3##""##S4##""##S5##""##S6##""##S7##""##S8##""##S9##""##S10
#endif

#if(CONFIG_METER_TYPE_SM39B==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "SM39B"
#elif(CONFIG_METER_TYPE_SM39C==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "SM39C"
#elif(CONFIG_METER_TYPE_SM39D==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "SM39D"
#elif(CONFIG_METER_TYPE_SM39E==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "SM39E"
#elif(CONFIG_METER_TYPE_SD39B==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "SD39B"
#elif(CONFIG_METER_TYPE_SD39C==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "SD39C"
#elif(CONFIG_METER_TYPE_SD39E==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "SD39E"
#elif(CONFIG_METER_TYPE_SM39F==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "SM39F"
#elif(CONFIG_METER_TYPE_SM39J==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "SM39J"
#elif(CONFIG_METER_TYPE_SM39H==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "SM39H"
#elif(CONFIG_METER_TYPE_SM39G==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "SM39G"
#elif(CONFIG_METER_TYPE_SM39I==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "SM39I"
#elif(CONFIG_METER_TYPE_SD39F==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "SD39F"
#elif(CONFIG_METER_TYPE_SM39K==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "SM39K"
#elif(CONFIG_METER_TYPE_SM39L==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "SM39L"
#elif(CONFIG_METER_TYPE_SM39M==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "SM39M"
#elif(CONFIG_METER_TYPE_METER==CONFIG_METER_TYPE)
    #define CONFIG_METER_SOFT_VER   "METER"
#else
    #define CONFIG_METER_SOFT_VER   "SX39X"
#endif

#if(CONFIG_METER_AREA_MODE_QUANGUO==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA  "A100"
#elif(CONFIG_METER_AREA_MODE_JIANGSU==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA  "C250"
#elif(CONFIG_METER_AREA_MODE_ZHEJIANG==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA  "C571"
#elif(CONFIG_METER_AREA_MODE_ZHEJIANG_NINGBO==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA  "0574"
#elif(CONFIG_METER_AREA_MODE_ZHEJIANG_HANGZHOU==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA  "0571"
#elif(CONFIG_METER_AREA_MODE_SHANGHAI==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA  "C210"
#elif(CONFIG_METER_AREA_MODE_SICHUAN==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA  "C280"
#elif(CONFIG_METER_AREA_MODE_JIANGXI==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA  "C791"
#elif(CONFIG_METER_AREA_MODE_HENAN==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA  "C371"
#elif(CONFIG_METER_AREA_MODE_HUBEI==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA  "C270"
#elif(CONFIG_METER_AREA_MODE_GUANGDONG==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA  "C200"
#elif(CONFIG_METER_AREA_MODE_QINGHAI==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA  "C971"
#elif(CONFIG_METER_AREA_MODE_SHANDONG==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA  "C531"
#elif(CONFIG_METER_AREA_MODE_HEBEI==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA  "C311"
#elif(CONFIG_METER_AREA_MODE_HUABEI==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA  "B100"
#elif(CONFIG_METER_AREA_MODE_SOUTHGRID==CONFIG_METER_AREA_MODE)
    #define CONFIG_METER_AREA_DATA  "B200"
#else
    #define CONFIG_METER_AREA_DATA  "0000"
#endif

#if(CONFIG_METER_SOFT_VER_V == 'A')
    #define CON_METER_SW_VER_STR    "A"
#elif(CONFIG_METER_SOFT_VER_V == 'B')
    #define CON_METER_SW_VER_STR    "B"
#elif(CONFIG_METER_SOFT_VER_V == 'C')
    #define CON_METER_SW_VER_STR    "C"
#elif(CONFIG_METER_SOFT_VER_V == 'D')
    #define CON_METER_SW_VER_STR    "D"
#elif(CONFIG_METER_SOFT_VER_V == 'E')
    #define CON_METER_SW_VER_STR    "E"
#elif(CONFIG_METER_SOFT_VER_V == 'F')
    #define CON_METER_SW_VER_STR    "F"
#elif(CONFIG_METER_SOFT_VER_V == 'V')
    #define CON_METER_SW_VER_STR    "V"
#else
    #define CON_METER_SW_VER_STR    "X"
#endif

#if(PROFUNCTION_METER_TYPE == PROFUNCTION_METER_TYPE_ALL)
#define METER_SW_FULL_VER_STR   STR_LINK10(CONFIG_METER_SOFT_VER,"-",CONFIG_METER_AREA_DATA,"-",CON_METER_SW_VER_STR,"",CON_PRO_METER_SET_VER_STR,"-",CON_PRO_METER_SET_DATE_STR,"-FF")
#else
#define METER_SW_FULL_VER_STR   STR_LINK10(CONFIG_METER_SOFT_VER,"-",CONFIG_METER_AREA_DATA,"-",CON_METER_SW_VER_STR,CON_PRO_METER_SET_VER_STR,"-",CON_PRO_METER_SET_DATE_STR,"-","%02x")
#endif

#if(CONFIG_METER_SW_DEBUG_MODE == GAL_YES)
#define METER_SW_BUILD_INF  STR_LINK4("Debug: ", __DATE__, "  ", __TIME__)
#else
#define METER_SW_BUILD_INF  STR_LINK4("Release: ", __DATE__, "  ", __TIME__)
#endif

#ifndef FLASH_COR
        #define FLASH_COR_INF   "Flash:AT"
#else
    #if(FLASH_COR == FLASH_ATMEL)
        #define FLASH_COR_INF   "Flash:AT"
    #elif(FLASH_COR == FLASH_WIBOND)
        #define FLASH_COR_INF   "Flash:WB"
    #elif(FLASH_COR == FLASH_ST)
        #define FLASH_COR_INF   "Flash:ST"
    #else
        #define FLASH_COR_INF   "Flash:UN"
    #endif
#endif

#if(CONFIG_METER_FLASH_MODE == CONFIG_METER_FLASH_MODE_1_45DB161_1_45DB321)
    #define FLASH_CONFIG_INF_STR    "-45 161+321"
#elif(CONFIG_METER_FLASH_MODE == CONFIG_METER_FLASH_MODE_2_45DB321)
    #define FLASH_CONFIG_INF_STR    "-45 321+321"
#elif(CONFIG_METER_FLASH_MODE == CONFIG_METER_FLASH_MODE_2_AT25FLASH)
    #define FLASH_CONFIG_INF_STR    "-25*2"
#elif(CONFIG_METER_FLASH_MODE == CONFIG_METER_FLASH_MODE_1_AT25FLASH)
    #define FLASH_CONFIG_INF_STR    "-25*1"
#endif

#if(CONFIG_METER_AUX_MODE == CONFIG_METER_AUX_MODE_DISABLE)
    #define METER_OTERH_INF_STR "Aux:Dis"
#else
    #define METER_OTERH_INF_STR "Aux:En "
#endif
//#define METER_SW_CON_INF1_STR   STR_LINK5("$", FLASH_COR_INF, FLASH_CONFIG_INF_STR," $", METER_OTERH_INF_STR)
#define METER_SW_CON_INF1_STR   STR_LINK2("  GCC:", __VERSION__)

const uchar TB_CON_METER_WARE_INF[][METER_CON_INF_STR_LENGTH]=
{

    /*METER_SW_VER_INF_ID,      */  METER_SW_FULL_VER_STR,
    /*METER_BUILT_TIME_ID£¬     */  METER_SW_BUILD_INF,
    /*METER_SW_CON_INF1_ID,     */  METER_SW_CON_INF1_STR,
    /*METER_PROTOCOL_VER_ID,    */  "DL/T645-2007",
    /*METER_FACTORY_INF_ID,     */  "PAX Electricity",
    /*METER_INF_CHECKINF_ID,    */  "By ZhangLong",
    /*METER_TYPE_INF_ID,        */  {0},
};
#endif

